# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valida < Formula
  desc "CLI Tools to automate API Testing based on OpenAPI Spec"
  homepage "https://github.com/valida-team/valida"
  version "0.0.15"

  on_macos do
    on_intel do
      url "https://github.com/valida-team/valida/releases/download/v0.0.15/valida_0.0.15_darwin_amd64.tar.gz"
      sha256 "1d879610ad97ee609d8f94e884eb9e24727d71e23680433be96d51873351816b"

      def install
        bin.install "valida"
      end
    end
    on_arm do
      url "https://github.com/valida-team/valida/releases/download/v0.0.15/valida_0.0.15_darwin_arm64.tar.gz"
      sha256 "b483797f7a4b0f95557c801c9de3b6a729e6b9164c0df132cee6bd310542171e"

      def install
        bin.install "valida"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valida-team/valida/releases/download/v0.0.15/valida_0.0.15_linux_amd64.tar.gz"
        sha256 "1dded273243c0a4c687901eb965047ec253a7e248878d7e51cf58e3a88d81697"

        def install
          bin.install "valida"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valida-team/valida/releases/download/v0.0.15/valida_0.0.15_linux_arm64.tar.gz"
        sha256 "dd53152f999d89ef932051a335624bc6189b7572d87033793a3fda86124fac33"

        def install
          bin.install "valida"
        end
      end
    end
  end
end
