# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Valida < Formula
  desc "CLI Tools to automate API Testing based on OpenAPI Spec"
  homepage "https://github.com/valida-team/valida"
  version "0.0.18"

  on_macos do
    on_intel do
      url "https://github.com/valida-team/valida/releases/download/v0.0.18/valida_0.0.18_darwin_amd64.tar.gz"
      sha256 "fd734c83c4eb4e031e0e9c2f57e172cfe01506f8bacae8605730fc5ad42a2d20"

      def install
        bin.install "valida"
      end
    end
    on_arm do
      url "https://github.com/valida-team/valida/releases/download/v0.0.18/valida_0.0.18_darwin_arm64.tar.gz"
      sha256 "27e053eab20d6704f1e88adc1436f438166a4d4c3ace2059519452d81856795b"

      def install
        bin.install "valida"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valida-team/valida/releases/download/v0.0.18/valida_0.0.18_linux_amd64.tar.gz"
        sha256 "75b4cedb59574760984cb2a56767ed35bc11fdc3e261e3a29a1a1cee379b5de0"

        def install
          bin.install "valida"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/valida-team/valida/releases/download/v0.0.18/valida_0.0.18_linux_arm64.tar.gz"
        sha256 "80535dff9da1cad8982d2a9eb8d033bf9bf90bf3214e31e6633ccb16694ed85d"

        def install
          bin.install "valida"
        end
      end
    end
  end
end
